"""records migration

Revision ID: 02c39f27a7a9
Revises: 88511d3129ea
Create Date: 2026-02-27 13:57:51.111583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c39f27a7a9'
down_revision = '88511d3129ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashtag', sa.String(), nullable=True),
    sa.Column('average_sleep', sa.String(), nullable=True),
    sa.Column('total_water_taken', sa.String(), nullable=True),
    sa.Column('total_exercise_time', sa.String(), nullable=True),
    sa.Column('total_meditation_time', sa.String(), nullable=True),
    sa.Column('low_moments', sa.String(), nullable=True),
    sa.Column('cope_up', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_userlogs_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userlogs')
    # ### end Alembic commands ###
