"""forth migration

Revision ID: 4c102dc92d7f
Revises: f840b3d38a53
Create Date: 2026-02-28 21:37:46.566194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c102dc92d7f'
down_revision = 'f840b3d38a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_of_the_day', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlogs', schema=None) as batch_op:
        batch_op.drop_column('quote_of_the_day')

    # ### end Alembic commands ###
